font_family    Monaco,Menlo,Consolas,"DejaVu Sans Mono",monospace
bold_font    auto
italic_font    auto
bold_italic_font    auto
font_size    12.0
force_ltr    no
disable_ligatures    always


remember_window_size    no
initial_window_width    1280
initial_window_height    998

background    #FFFFFF
foreground    #000000
cursor    #FF0000
cursor_text_color    #FFFFFF
cursor_shape    block
cursor_beam_thickness    3.0

hide_window_decorations    yes
window_border_width    5
active_border_color    #FF6B00
inactive_border_color    #CCCCCC

scrollback_lines    9999
wheel_scroll_multiplier    4.0
scrollbar    never
scrollbar_interactive    yes

enable_audio_bell    no

window_border_width    0.5pt
draw_minimal_borders    yes
window_margin_width    0

include /home/zzz/.config/kitty/themes.conf
