
LEFT seek -1
RIGHT seek 3

WHEEL_UP seek 3
WHEEL_DOWN seek -1

MBTN_RIGHT playlist-next
MBTN_LEFT_DBL playlist-prev
#Shift+MBTN_RIGHT playlist-prev

MBTN_MID cycle pause
MBTN_FORWARD seek 90 exact
#MBTN_FORWARD playlist-next
MBTN_BACK seek -87
#MBTN_BACK playlist-prev

#Shift+WHEEL_UP seek 90 exact
#Shift+WHEEL_DOWN seek -87

