# 颜色主题（Nord ）
color_focus         = rgb:fb/c2/97
color_unfocus       = rgb:3c/38/36
#border_width        = 0
border_width        = 2
tile_gap            = 4
region_padding      = 24
bar_enabled         = 0        # 关闭自带bar
#bar_at_bottom       = 0
#bar_border_width    = 0
#bar_font            = fixed:pixelsize=1   
#bar_format          = ' '
#bar_offset_y        = -1        

# 用 Win 键做 Mod
modkey              = Mod4

# 常用程序
program[term]           = /home/alex/bin/kitty-chinese.sh
program[alacritty]      = /usr/local/bin/alacritty
program[browser]        = /usr/local/bin/firefox
program[neovim]         = /usr/local/bin/nvim-qt
program[rofi_drun]      = /usr/local/bin/rofi -show drun -theme gruvbox-dark -show-icons
program[rofi_run]       = /usr/local/bin/rofi -show run -theme gruvbox-dark -show-icons
program[rofi_window]    = /usr/local/bin/rofi -show window -theme gruvbox-dark -show-icons
program[lock]           = /usr/X11R6/bin/xlock

# 系统快捷键
bind[quit]                      = MOD+Shift+q        # 退出 spectrwm（官方默认未绑定）
bind[restart]                   = MOD+Shift+r        # 重启 spectrwm
bind[wind_del]                  = MOD+q              # 关闭当前窗口
# 布局操作
bind[cycle_layout]              = MOD+s              # 循环切换到下一个布局（vertical / horizontal）
bind[flip_layout]               = MOD+Shift+space    # 翻转布局
bind[layout_vertical]           = MOD+v              # 切换到垂直布局                
bind[layout_horizontal]         = MOD+h              # 切换到水平布局 
bind[layout_floating]           = MOD+i              # 切换到浮动布局（窗口可以自由拖动和调整大小）
bind[stack_reset]               = MOD+0              # 重置布局 
# 窗口操作
bind[swap_main]                 = MOD+Return         # 与 master 窗口交换位置
bind[maximize_toggle]           = MOD+f              # 窗口最大化
bind[fullscreen_toggle]         = MOD+Shift+f        # 全屏
bind[master_shrink]             = MOD+p              # 主窗口缩小
bind[master_grow]               = MOD+o              # 主窗口扩大
bind[stack_inc]                 = MOD+Shift+i        # 增加 stack 区窗口数
bind[stack_dec]                 = MOD+Shift+d        # 减少 stack 区窗口数
bind[master_add]                = MOD+u              # 主区域增加窗口
bind[master_del]                = MOD+b              # 主区域减少窗口
bind[focus_next]                = MOD+j              # 聚焦下一个窗口
bind[focus_prev]                = MOD+k              # 聚焦上一个窗口
bind[focus_main]                = MOD+a              # 聚焦到主窗口
bind[float_toggle]              = MOD+l              # 切换窗口的平铺/浮动状态
bind[free_toggle]               = MOD+y              # 切换窗口的工作区/自由模式

# 程序快捷键
bind[term]          = Mod+Shift+Return
bind[alacritty]     = Mod+t
bind[browser]       = Mod+m
bind[neovim]        = Mod+n
bind[rofi_drun]     = Mod+r
bind[rofi_run]      = Mod+e
bind[rofi_window]   = Mod+w
bind[lock]          = Mod+Shift+l

# 工作区 & 导航
workspace_limit         = 9
bind[ws_1]              = Mod+1
bind[ws_2]              = Mod+2
bind[ws_3]              = Mod+3
bind[ws_4]              = Mod+4
bind[ws_5]              = Mod+5
bind[ws_6]              = Mod+6
bind[ws_7]              = Mod+7
bind[ws_8]              = Mod+8
bind[ws_9]              = Mod+9
bind[mvws_1]            = MOD+Shift+1
bind[mvws_2]            = MOD+Shift+2
bind[mvws_3]            = MOD+Shift+3
bind[mvws_4]            = MOD+Shift+4
bind[mvws_5]            = MOD+Shift+5
bind[mvws_6]            = MOD+Shift+6
bind[mvws_7]            = MOD+Shift+7
bind[mvws_8]            = MOD+Shift+8
bind[mvws_9]            = MOD+Shift+9
bind[name_workspace]    = MOD+Shift+n       # 工作区重命名

