unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse off

set -g status-bg black
set -g status-fg white

set -g pane-border-style fg=green
set -g pane-active-border-style fg=red

set -g base-index 1
setw -g pane-base-index 1
