;
;    ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;   ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;   ██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;   ██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;    ██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
;    ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[colors]

fg-blue = #5294e2
focus-dark = #1b2124
blue = #73d0ff
blue-darker = #0771ed
green = #bae67e
dark-green = #75c933
red = #ff3333
bg = #800A0E14
fg = #bfbab0
cyan = #95e6cb
alpha = #00000000
white = #fff

;; colors
; night
; storm
teal = #1ABC9C