
mime ^text, label editor = $EDITOR -- "$@"

mime ^video|audio, has mpv, X, flag r = mpv --autofit=70% --fs=no --volume=30 -- "$0"

ext pdf, has xreader, X, flag f = xreader "$@"

mime ^image, has feh, X, flag f = feh -- "$@"

mime ^ranger/x-terminal-emulator, has kitty = kitty -- "$@"
