#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III

bspc config border_width         2 # 所有窗口的边框宽度为 2 px
bspc config window_gap          8 # 窗口之间的间距（gap）为 8 px

bspc config split_ratio          0.52 # 新窗口加入时，父节点按 0.52 : 0.48 的比例划分空间（略偏向新窗口）
bspc config borderless_monocle   true # 当 desktop 处于 monocle（全屏层叠）模式时隐藏边框
bspc config gapless_monocle      true # 当 desktop 处于 monocle（全屏层叠）模式时同时去掉 gap，让当前窗口真正占满整个屏幕

# 1. 完全禁用焦点跟随鼠标
bspc config focus_follows_pointer false
# 2. 指针不跟随焦点变化
bspc config pointer_follows_focus false
# 3. 指针不跟随显示器焦点变化
bspc config pointer_follows_monitor false
# 4. 设置焦点延迟（毫秒）
# bspc config focus_delay 300
# 5. 禁用自动切换焦点
# bspc config focus_by_distance true
# 设置为 false 可减少意外焦点切换
bspc config focus_by_distance false

# state=tiled|pseudo_tiled|floating|fullscreen
bspc rule -a firefox desktop='^2' state=tiled
bspc rule -a Alacritty desktop='^1' state=pseudo_tiled focus=on follow=on center=on
bspc rule -a kitty desktop='^1' state=pseudo_tiled focus=on
bspc rule -a mpv state=floating focus=on
bspc rule -a subl desktop='^3'
bspc rule -a Xed desktop='^3'
bspc rule -a Xreader desktop='^3'
bspc rule -a emacs desktop='^3' state=pseudo_tiled focus=on
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off # 屏幕键盘/按键可视化，不受 bspwm 管理，避免被平铺/最小化


# Border
#bspc config focused_border_color        "#6c71c4"
#bspc config normal_border_color         "#073642"
#bspc config active_border_color         "#073642"

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
#bspc config active_border_color "#6272a4"
bspc config focused_border_color "#ff79c6"
#bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

setxkbmap -option ""
setxkbmap -option "caps:ctrl_modifier,ctrl:nocaps"
xset dpms 1200 1200 1200

# Wallpaper
# nitrogen --restore &
feh --bg-fill ~/Pictures/wallpapers/forest-foggy-misty-cloudy.jpg &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
# ~/.config/bspwm/scripts/low_bat_notifier.sh

